### ISSUE TITLE
Track name only shows on mouse-over in bottom play bar

### ISSUE THREAD

**Issue by jberkus** [voltraco/beta#23]
The "play bar" displays on the bottom of the Voltra window constantly, as it should.  However, for some reason, the track name now only displays on mouse-over; otherwise, it's invisible.   This seems like a strange design choice; why not display the track name all the time?

Pretty sure this is a change in beta2.20, but not sure.

Platform: Fedora 24 Linux, Gnome 3, AppImage.

**Comment by aprile** [comment]
This has been that way for quite a while actually, and it was an intentional decision to keep everything clean and balanced. 

I find it's not something I always need to see, and when I want to see the song name I can just hover over it, or just have the queue open! Is this something you feel should be visible always?

**Comment by jberkus** [comment]
@aprileelcich I would prefer to have it visible always.  Or to put it another way: it seems very odd to display the number of minutes in the song, but not the song name.

Mind you, the only reason I noticed this is because of Issue #22, so if that issue gets fixed I might go back to not caring.

**Comment by aprileelcich** [comment]
Does the song highlighting appear again when you restart the app?

**Comment by heapwolf** [comment]
Fixed.
